# Generated by Django 5.0.4 on 2024-06-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('brand_name', models.CharField(max_length=200)),
                ('product_inventory', models.IntegerField()),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('featured_image1', models.ImageField(upload_to='product/main_images/%Y/%m/%d/')),
                ('featured_image2', models.ImageField(upload_to='product/main_images/%Y/%m/%d/')),
                ('featured_image3', models.ImageField(upload_to='product/main_images/%Y/%m/%d/')),
                ('featured_image4', models.ImageField(upload_to='product/main_images/%Y/%m/%d/')),
                ('featured_image5', models.ImageField(upload_to='product/main_images/%Y/%m/%d/')),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': '5. Products',
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
