# Generated by Django 5.0.4 on 2024-06-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_featured_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=200)),
                ('featured_1', models.ManyToManyField(to='blog.product')),
            ],
            options={
                'verbose_name': 'featured',
                'verbose_name_plural': '3. Featured List',
            },
        ),
        migrations.DeleteModel(
            name='Featured',
        ),
    ]
