# Generated by Django 5.0.4 on 2024-06-04 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_carousellist_delete_featured'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarouselList',
        ),
    ]
