# Generated by Django 5.0.4 on 2024-06-05 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_featured_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='featured_list',
            name='featured_product_10',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Featured_product_10', to='blog.product'),
        ),
        migrations.AddField(
            model_name='featured_list',
            name='featured_product_2',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Featured_product_2', to='blog.product'),
        ),
        migrations.AddField(
            model_name='featured_list',
            name='featured_product_3',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Featured_product_3', to='blog.product'),
        ),
        migrations.AddField(
            model_name='featured_list',
            name='featured_product_4',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Featured_product_4', to='blog.product'),
        ),
        migrations.AddField(
            model_name='featured_list',
            name='featured_product_5',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Featured_product_5', to='blog.product'),
        ),
        migrations.AddField(
            model_name='featured_list',
            name='featured_product_6',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Featured_product_6', to='blog.product'),
        ),
        migrations.AddField(
            model_name='featured_list',
            name='featured_product_7',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Featured_product_7', to='blog.product'),
        ),
        migrations.AddField(
            model_name='featured_list',
            name='featured_product_8',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Featured_product_8', to='blog.product'),
        ),
        migrations.AddField(
            model_name='featured_list',
            name='featured_product_9',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Featured_product_9', to='blog.product'),
        ),
        migrations.AlterField(
            model_name='featured_list',
            name='featured_product_1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Featured_Product_1', to='blog.product'),
        ),
    ]
