# Generated by Django 5.0.4 on 2024-06-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_featured_list_featured_product_10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featured_list',
            name='featured_product_1',
        ),
        migrations.RemoveField(
            model_name='featured_list',
            name='featured_product_10',
        ),
        migrations.RemoveField(
            model_name='featured_list',
            name='featured_product_2',
        ),
        migrations.RemoveField(
            model_name='featured_list',
            name='featured_product_3',
        ),
        migrations.RemoveField(
            model_name='featured_list',
            name='featured_product_4',
        ),
        migrations.RemoveField(
            model_name='featured_list',
            name='featured_product_5',
        ),
        migrations.RemoveField(
            model_name='featured_list',
            name='featured_product_6',
        ),
        migrations.RemoveField(
            model_name='featured_list',
            name='featured_product_7',
        ),
        migrations.RemoveField(
            model_name='featured_list',
            name='featured_product_8',
        ),
        migrations.RemoveField(
            model_name='featured_list',
            name='featured_product_9',
        ),
        migrations.AddField(
            model_name='featured_list',
            name='featured_product_1',
            field=models.ManyToManyField(default='', related_name='Featured_Product_1', to='blog.product'),
        ),
        migrations.AddField(
            model_name='featured_list',
            name='featured_product_10',
            field=models.ManyToManyField(default='', related_name='Featured_product_10', to='blog.product'),
        ),
        migrations.AddField(
            model_name='featured_list',
            name='featured_product_2',
            field=models.ManyToManyField(default='', related_name='Featured_product_2', to='blog.product'),
        ),
        migrations.AddField(
            model_name='featured_list',
            name='featured_product_3',
            field=models.ManyToManyField(default='', related_name='Featured_product_3', to='blog.product'),
        ),
        migrations.AddField(
            model_name='featured_list',
            name='featured_product_4',
            field=models.ManyToManyField(default='', related_name='Featured_product_4', to='blog.product'),
        ),
        migrations.AddField(
            model_name='featured_list',
            name='featured_product_5',
            field=models.ManyToManyField(default='', related_name='Featured_product_5', to='blog.product'),
        ),
        migrations.AddField(
            model_name='featured_list',
            name='featured_product_6',
            field=models.ManyToManyField(default='', related_name='Featured_product_6', to='blog.product'),
        ),
        migrations.AddField(
            model_name='featured_list',
            name='featured_product_7',
            field=models.ManyToManyField(default='', related_name='Featured_product_7', to='blog.product'),
        ),
        migrations.AddField(
            model_name='featured_list',
            name='featured_product_8',
            field=models.ManyToManyField(default='', related_name='Featured_product_8', to='blog.product'),
        ),
        migrations.AddField(
            model_name='featured_list',
            name='featured_product_9',
            field=models.ManyToManyField(default='', related_name='Featured_product_9', to='blog.product'),
        ),
    ]
