# Generated by Django 5.0.4 on 2024-06-05 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_list_name', models.CharField(max_length=100)),
                ('banner_1', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Banner_1', to='blog.banner')),
                ('banner_2', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Banner_2', to='blog.banner')),
                ('banner_3', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Banner_3', to='blog.banner')),
                ('banner_4', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Banner_4', to='blog.banner')),
            ],
        ),
    ]
