# Generated by Django 5.0.4 on 2024-06-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_banner_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='banner_image',
            field=models.ImageField(blank=True, default='', upload_to='banners/%Y/%m/%d/'),
        ),
    ]
