# Generated by Django 5.0.4 on 2024-06-05 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_banner_list_banner_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner_list',
            name='banner_2',
            field=models.ForeignKey(default='', limit_choices_to=models.Q(('banner_image', ''), _negated=True), on_delete=django.db.models.deletion.CASCADE, related_name='Banner_2', to='blog.product'),
        ),
        migrations.AlterField(
            model_name='banner_list',
            name='banner_3',
            field=models.ForeignKey(default='', limit_choices_to=models.Q(('banner_image', ''), _negated=True), on_delete=django.db.models.deletion.CASCADE, related_name='Banner_3', to='blog.product'),
        ),
        migrations.AlterField(
            model_name='banner_list',
            name='banner_4',
            field=models.ForeignKey(default='', limit_choices_to=models.Q(('banner_image', ''), _negated=True), on_delete=django.db.models.deletion.CASCADE, related_name='Banner_4', to='blog.product'),
        ),
    ]
