# Generated by Django 5.0.4 on 2024-06-05 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_banner_list_banner_2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
