# Generated by Django 5.0.4 on 2024-06-06 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_remove_product_brand_name_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='BrandName', to='blog.brand'),
        ),
    ]
