# Generated by Django 5.0.4 on 2024-06-06 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_alter_product_brand_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand_name',
        ),
        migrations.AddField(
            model_name='product',
            name='brand_namee',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BrandName', to='blog.brand'),
        ),
    ]
