# Generated by Django 5.0.4 on 2024-06-06 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_remove_product_brand_name_product_brand_namee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_namee',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='BrandName', to='blog.brand'),
        ),
    ]
