# Generated by Django 5.0.4 on 2024-06-06 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_alter_product_brand_namee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_namee',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='BrandName', to='blog.brand'),
        ),
    ]
