# Generated by Django 5.0.4 on 2024-06-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_alter_product_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('starter_kits', 'Starter Kits'), ('devices', 'Devices'), ('tanks', 'Tanks'), ('accessories', 'Accessories'), ('e-liquids', 'E-Liquids'), ('alternatives', 'Alternatives'), ('disposables', 'Disposables')], default='e-liquids', max_length=20),
        ),
    ]
