# Generated by Django 5.0.4 on 2024-06-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('starter_kits', 'Starter Kits'), ('devices', 'Devices'), ('tanks', 'Tanks'), ('accessories', 'Accessories'), ('e-liquids', 'E-Liquids'), ('alternatives', 'Alternatives'), ('disposables', 'Disposables')], max_length=20, null=True),
        ),
    ]
