# Generated by Django 5.0.4 on 2024-06-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('starter_kits', 'Starter Kits'), ('devices', 'Devices'), ('tanks', 'Tanks'), ('accessories', 'Accessories'), ('e-liquids', 'E-Liquids'), ('alternatives', 'Alternatives'), ('disposables', 'Disposables')], default='e-liquids', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
