# Generated by Django 5.0.4 on 2024-06-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battery_Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=200)),
            ],
        ),
    ]
