# Generated by Django 5.0.4 on 2024-06-08 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_battery_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='device_battery_capacity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='BatteryCapacity', to='blog.battery_capacity'),
        ),
        migrations.AddField(
            model_name='product',
            name='device_battery_size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='BatterySize', to='blog.battery_size'),
        ),
        migrations.AddField(
            model_name='product',
            name='device_battery_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='BatteryType', to='blog.battery_type'),
        ),
        migrations.AddField(
            model_name='product',
            name='device_features',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='DeviceFeatures', to='blog.features'),
        ),
        migrations.AddField(
            model_name='product',
            name='device_max_wattage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='MaxWattage', to='blog.max_wattage'),
        ),
        migrations.AddField(
            model_name='product',
            name='device_screen_size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ScreenSize', to='blog.screen_size'),
        ),
    ]
