# Generated by Django 5.0.4 on 2024-06-09 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_product_device_battery_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='device_battery_capacity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='device_features',
        ),
        migrations.RemoveField(
            model_name='product',
            name='device_screen_size',
        ),
    ]
