# Generated by Django 5.0.4 on 2024-06-09 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_remove_product_device_battery_capacity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Battery_Capacity',
        ),
        migrations.DeleteModel(
            name='Features',
        ),
        migrations.DeleteModel(
            name='Screen_Size',
        ),
    ]
