# Generated by Django 5.0.4 on 2024-06-11 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_alter_battery_type_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='device_battery_size',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BatterySize', to='blog.battery_size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='device_max_wattage',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MaxWattage', to='blog.max_wattage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='disposable_ejuice_capacity',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DisposableEJuiceCapacity', to='blog.disposable_ejuice_capacity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='disposable_flavor',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DisposableFlavor', to='blog.disposable_flavor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='disposable_puff_count',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DisposablePuffCount', to='blog.disposable_puff_count'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ejuice_bottle_size',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EJuiceBottleSize', to='blog.ejuice_bottle_size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ejuice_flavor',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EJuiceFlavor', to='blog.ejuice_flavor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ejuice_nicotine_amount',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EJuiceNicotineAmount', to='blog.ejuice_nicotine_amount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ejuice_salt_nicotine',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EJuiceSaltNicotine', to='blog.ejuice_salt_nicotine'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ejuice_sub_ohm',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EJuiceSubOhm', to='blog.ejuice_sub_ohm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ejuice_tobacco_free',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EJuiceTobaccoFree', to='blog.ejuice_tobacco_free'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tank_airflow_style',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TankAirflowStyle', to='blog.tank_airflow_style'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tank_capacity',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TankCapity', to='blog.tank_capacity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tank_coil_style',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TankCoilStyle', to='blog.tank_coil_style'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tank_drip_tip',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TankDripTip', to='blog.tank_drip_tip'),
        ),
    ]
