# Generated by Django 5.0.4 on 2024-06-11 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_alter_product_device_battery_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery_size',
            name='option',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='disposable_ejuice_capacity',
            name='option',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='disposable_flavor',
            name='option',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='disposable_puff_count',
            name='option',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='ejuice_bottle_size',
            name='option',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='ejuice_flavor',
            name='option',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='ejuice_nicotine_amount',
            name='option',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='ejuice_salt_nicotine',
            name='option',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='ejuice_sub_ohm',
            name='option',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='ejuice_tobacco_free',
            name='option',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='max_wattage',
            name='option',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='device_battery_size',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BatterySize', to='blog.battery_size', to_field='option'),
        ),
        migrations.AlterField(
            model_name='product',
            name='device_battery_type',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BatteryType', to='blog.battery_type', to_field='option'),
        ),
        migrations.AlterField(
            model_name='product',
            name='device_max_wattage',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MaxWattage', to='blog.max_wattage', to_field='option'),
        ),
        migrations.AlterField(
            model_name='product',
            name='disposable_ejuice_capacity',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DisposableEJuiceCapacity', to='blog.disposable_ejuice_capacity', to_field='option'),
        ),
        migrations.AlterField(
            model_name='product',
            name='disposable_flavor',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DisposableFlavor', to='blog.disposable_flavor', to_field='option'),
        ),
        migrations.AlterField(
            model_name='product',
            name='disposable_puff_count',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DisposablePuffCount', to='blog.disposable_puff_count', to_field='option'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ejuice_bottle_size',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EJuiceBottleSize', to='blog.ejuice_bottle_size', to_field='option'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ejuice_flavor',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EJuiceFlavor', to='blog.ejuice_flavor', to_field='option'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ejuice_nicotine_amount',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EJuiceNicotineAmount', to='blog.ejuice_nicotine_amount', to_field='option'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ejuice_salt_nicotine',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EJuiceSaltNicotine', to='blog.ejuice_salt_nicotine', to_field='option'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ejuice_sub_ohm',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EJuiceSubOhm', to='blog.ejuice_sub_ohm', to_field='option'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ejuice_tobacco_free',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EJuiceTobaccoFree', to='blog.ejuice_tobacco_free', to_field='option'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tank_airflow_style',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TankAirflowStyle', to='blog.tank_airflow_style', to_field='option'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tank_capacity',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TankCapity', to='blog.tank_capacity', to_field='option'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tank_coil_style',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TankCoilStyle', to='blog.tank_coil_style', to_field='option'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tank_drip_tip',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TankDripTip', to='blog.tank_drip_tip', to_field='option'),
        ),
        migrations.AlterField(
            model_name='tank_airflow_style',
            name='option',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='tank_capacity',
            name='option',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='tank_coil_style',
            name='option',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='tank_drip_tip',
            name='option',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
