# Generated by Django 5.0.4 on 2024-06-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0049_alter_brand_name_alter_product_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.FloatField(default=1),
        ),
    ]
